export const DI_CONSTANTS = {
  HttpService: 'HttpService',
  ExchangeManagerHttpService: 'ExchangeManagerHttpService',
  FileManagerHttpService: 'FileManagerHttpService',
  UserHttpService: 'UserHttpService',
  CacheService: 'CacheService',
  TranslationService: 'TranslationService',
  StorageService: 'StorageService',
  SessionStorageService: 'SessionStorageService',
  LocalStorageService: 'LocalStorageService',
  ResourceManagerRepository: 'ResourceManagerRepository',
  ExchangeManagerRepository: 'ExchangeManagerRepository',
  ResourceManagerUseCase: 'ResourceManagerUseCase',
  FileManagerUseCase: 'FileManagerUseCase',
  FileManagerRepository: 'FileManagerRepository',
  TranslationUseCase: 'TranslationUseCase',
  PageConfigsUseCase: 'PageConfigsUseCase',
  ExchangeManagerUseCase: 'ExchangeManagerUseCase',
  UserRepository: 'UserRepository',
  PageConfigsRepository: 'PageConfigsRepository'
};
