# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr:
 branches:
   exclude:
     - develop
     
trigger:
  branches:
    include:
      - develop
  batch: true
  paths:
    include:
      - src/ResourceManager

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  acr: 'bangits.azurecr.io/'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - checkout:  self
      submodules: false
      persistCredentials: true

    - task: DockerCompose@0
      displayName: 'Build services'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'AtomContainerRegistration'
        dockerComposeFileArgs: |
          TAG=1.0.$(Build.BuildId)
          PROJECT=enterprise-hub/$(Build.SourceBranchName)/
          DOCKER_REGISTRY=$(acr)
        projectName: '$(Build.Repository.Name)/$(Build.SourceBranchName)/'
        action: 'Build services'
        arguments: resourceManager.api

    - task: DockerCompose@0
      displayName: 'Publish services'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'AtomContainerRegistration'
        dockerComposeFile: 'docker-compose.yml'
        dockerComposeFileArgs: |
          TAG=1.0.$(Build.BuildId)
          PROJECT=atom/$(Build.SourceBranchName)/
          DOCKER_REGISTRY=$(acr)
        projectName: '$(Build.Repository.Name)/$(Build.SourceBranchName)/'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'push resourceManager.api'
