apiVersion: v1
kind: Service
metadata:
    name: "atomaks-a651"
    labels:
        app: "atomaks-a651"
spec:
    type: LoadBalancer
    ports:
    - port: 6001
      targetPort: 6001
      protocol: TCP
      name: http
    selector:
        app: "atomaks-a651"